### PR TITLE
turkish localization

### PR DESCRIPTION
**Pull request by egek92**

### CODE REVIEW

**Comment by egek92** [comment]
added 3 string resources just to change "select country", "no results found" and "search" texts

**Comment by joielechong** [comment]
Thank you for the PR, but I can't merge this because it won't integrate with the current library. Could you translate both the  `library/src/main/res/values/strings.xml` and `library/src/main/res/values/strings_country.xml` so I can merge your PR? You can create the Turkish translation to `library/src/main/res/values-tr_TR/`

**Comment by egek92** [comment]
[values-tr.zip](https://github.com/joielechong/CountryCodePicker/files/2061983/values-tr.zip)
here is values-tr if you want to add, cheers

**Comment by joielechong** [comment]
Thank you for the translation. I have added it and adding your user name to credit ;)

**Pull request closed without merging**
