### PR TITLE
Fix country code for Sint Maarten

### PR DESCRIPTION
**Pull request by tejasna**
Change country code for Sint Marteen to [1721](https://countrycode.org/sintmaarten)

### CODE REVIEW

**Comment by zeno-mir** [comment]
@joielechong any chance you could merge this PR please?

**Comment by joielechong** [comment]
Thank you for the PR and very sorry for the super late response :(. So many things changes need to be fixed on my life for the couple months.

**Comment by zeno-mir** [comment]
No worries @joielechong, better late than never 😄 I know how hard it is sometimes to find the time to work on side projects. Many thanks for accepting this PR, it's a great library!

Hope all is good with you, keep safe and keep healthy ❤️

**Comment by joielechong** [comment]
@zeno-mir Thank you very much for the appreciation :smile: :smile: :smile: .

Now is really tough situation for everyone, and it's scary..

I hope everything is going well on your side.
GBU

**Pull request merged**
